### ISSUE TITLE
cimguizmo.h:95 random `]]` as return type appears

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimguizmo#3]
to reproduce:
```sh
cd ImGuizmo
git checkout master
cd ../generator
sh generator.sh
cat ../cimguizmo.h |head -n95 |tail -n1
```

will give you 
```h
CIMGUI_API ]] void ImGuizmo_deprecated("Use PushID/PopID instead.");
```

**Comment by sonoro1234** [comment]
fixed now. There were some cpp attributes `[[deprecated("Use PushID/PopID instead.")]]` that had to be deleted.

**Comment by gucio321** [comment]
thank you!

**Comment by sonoro1234** [comment]
Your cimguizmo repo is not a fork of this repo but a remix of other cimgui repos. It seems very inconvinient in order to use future cimguizmo (or cimgui) modifications. It also can lead to other people using your repo without knowing it is not the original cimguizmo repo.

**Comment by gucio321** [comment]
yes, sorry I forgot about it, I'll remove it.

**Comment by gucio321** [comment]
ok, now gucio321/cimguizmo is a fork of this and the old version is cimguizmo-old and is private archive.
